server:
  port: 8082


spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://mysql:3306/master?setUnicode=true&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
    username: master
    password: pZdxysqJX4bK4VrB
    connectionTimeout: 2000
    maximumPoolSize: 100
    minimumIdle: 5
  #redis配置
  redis:
    database: 0
    host: redis
    port: 6379
    lettuce:
      pool:
        min-idle: 100
        max-wait: 3000
        max-idle: 100
        max-total: 1000
    timeout: 5000

#日志配置
logging:
  level:
    com.javademo.feign: debug
  config: classpath:log4j2.xml

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #目的是为了省略resultType里的代码量
#  type-aliases-package: com.javademo.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl