server:
  port: 8082


spring:
  redis:
    database: 0
    host: redis
    port: 6379
    lettuce:
      pool:
        min-idle: 100
        max-wait: 3000
        max-idle: 100
        max-total: 1000
    timeout: 5000
logging:
  level:
    com.javademo.feign: debug
  config: classpath:log4j2.xml